<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../InkjetOperator/Managers/TcpManager.cs" Link="TcpManager.cs" />
    <Compile Include="../../InkjetOperator/Services/UvTcpService.cs" Link="UvTcpService.cs" />
    <Compile Include="../../InkjetOperator/Services/McProtocolService.cs" Link="McProtocolService.cs" />
    <Compile Include="../../InkjetOperator/Services/PushButtonWatcher.cs" Link="PushButtonWatcher.cs" />
    <Compile Include="../../InkjetOperator/Services/PushButtonSettings.cs" Link="PushButtonSettings.cs" />
  </ItemGroup>
</Project>
